services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: day49-api
    ports:
      - "8091:8080"
    environment:
      SERVICE_NAME: compose-api
      ENVIRONMENT: production
    volumes:
      - day49-shared-data:/shared
    depends_on:
      - worker

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: day49-worker
    environment:
      WORKER_NAME: compose-worker
    volumes:
      - day49-shared-data:/shared

volumes:
  day49-shared-data:
