name: Database Migrations

on:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Flyway Migrations
        uses: redgate/flyway-action@1
        with:
          url: 'jdbc:postgresql://${{ secrets.DB_HOST }}:5432/postgres'
          user: 'postgres'
          password: ${{ secrets.DB_PASSWORD }}
          locations: 'filesystem:days-98-db-migrations/db/migration'
          command: 'migrate'
